<a href="https://colab.research.google.com/github/S-Chaudhuri/ml/blob/main/tensorflow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("Tensorflow version =",tf.__version__)

Tensorflow version = 2.8.2


In [7]:
mnist=tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train,x_test=x_train/255.0,x_test/255.0

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10)
])

In [8]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.54226255, -0.89984864,  0.7843744 ,  0.89637786, -0.14374265,
         0.03757451, -0.20932864, -0.05686759,  0.3400067 , -0.5912052 ]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.13884518, 0.0328269 , 0.17687994, 0.19784318, 0.06992017,
        0.08381998, 0.06548154, 0.07626615, 0.11342065, 0.04469634]],
      dtype=float32)

In [15]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2559 - accuracy: 0.9267
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1115 - accuracy: 0.9670
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0770 - accuracy: 0.9767
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0569 - accuracy: 0.9824
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0447 - accuracy: 0.9859


In [17]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0758 - accuracy: 0.9788 - 703ms/epoch - 2ms/step


[0.0758260115981102, 0.9787999987602234]

In [18]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [19]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.0063903e-08, 5.7812368e-09, 4.7262256e-06, 1.8865207e-05,
        7.6101267e-13, 1.6264183e-08, 4.1943665e-13, 9.9997592e-01,
        1.2103798e-07, 3.5225256e-07],
       [9.2384802e-09, 2.5976021e-04, 9.9970716e-01, 3.2332442e-05,
        5.7437020e-13, 2.5607036e-07, 2.9517045e-08, 2.6318578e-12,
        4.2521594e-07, 2.4829246e-13],
       [5.9641059e-07, 9.8486161e-01, 2.0169483e-03, 5.4469338e-04,
        1.1020673e-04, 2.5285268e-04, 2.6676655e-04, 2.5942104e-03,
        9.3318075e-03, 2.0331870e-05],
       [9.9996150e-01, 1.1165826e-08, 6.0303259e-06, 4.7594781e-08,
        1.1044015e-08, 1.3788718e-06, 1.4541202e-05, 1.4200225e-05,
        3.8249448e-09, 2.2454824e-06],
       [1.5830160e-06, 7.5793949e-09, 1.7551757e-06, 2.8203278e-08,
        9.9897397e-01, 3.2224026e-08, 1.4003962e-06, 2.1825370e-05,
        1.6155587e-07, 9.9929166e-04]], dtype=float32)>